# Generated by Django 3.1.1 on 2020-09-25 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_Names', models.CharField(max_length=50)),
                ('school_adress', models.TextField(max_length=500)),
            ],
            options={
                'ordering': ['school_Names'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.TextField(max_length=200)),
            ],
            options={
                'ordering': ['subject_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_names', models.CharField(max_length=300)),
                ('mobile_number', models.IntegerField()),
                ('alternate_number', models.IntegerField()),
                ('school', models.ManyToManyField(to='myapp.Scholl')),
            ],
            options={
                'ordering': ['student_names'],
            },
        ),
        migrations.AddField(
            model_name='scholl',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subject'),
        ),
    ]
