# Generated by Django 3.1.1 on 2020-09-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholl',
            name='subject',
        ),
        migrations.AddField(
            model_name='scholl',
            name='subject',
            field=models.ManyToManyField(to='myapp.Subject'),
        ),
    ]
